# Generated by Django 3.0.3 on 2022-01-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='DevRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('dev1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers_as_dev1', to='developers.Dev')),
                ('dev2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers_as_dev2', to='developers.Dev')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='dev',
            name='organizations',
            field=models.ManyToManyField(to='developers.Organization'),
        ),
    ]
