# Generated by Django 3.0.3 on 2022-01-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devregister',
            options={'ordering': ['registered_at']},
        ),
        migrations.AddField(
            model_name='devregister',
            name='organizations',
            field=models.ManyToManyField(to='developers.Organization'),
        ),
    ]
